alter PROC FI_SP_IncBeneficiarioV1
    @NOME          VARCHAR (50) ,
    @IDCLIENTE     BIGINT,
    @CPF           VARCHAR (11)
AS
BEGIN
	INSERT INTO BENEFICIARIOS (NOME, CPF, IDCLIENTE) 
	VALUES (@NOME, @CPF,@IDCLIENTE )

	SELECT SCOPE_IDENTITY()
END