name: CI-DI
on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Exemplo
        run: echo "pipeline"
      - name: Checkout
        uses: actions/checkout@v4.1.7
       
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push        
        uses: docker/build-push-action@v6
        with:
          context: ./FI.WebAtividadeEntrevista
          push: true
          file: ./FI.WebAtividadeEntrevista/Dockerfile
          tags: |
            WebAtividade:latest
            WebAtividade:${{ github.run_number }}
